config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/mybookings", to: "bookings#my_bookings"
  get "/rentyourcar", to: "bookings#rent_your_car"
  patch "/mybookings/:booking_id", to: "bookings#update"

  resources :cars do
    member do 
      get "booking", to: "bookings#create"
    end
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :car_id, uniqueness: { scope: :user_id }
end

app/models/car.rb
class Car < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  include PgSearch
  pg_search_scope :search_by_address,
    against: [ :address ],
    using: {
      tsearch: { prefix: true } 
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: [:create, :new, :destroy, :edit ]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address])
  end

  protected
    def after_sign_in_path_for(resource)
      request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    end
    
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def create
    @car = Car.find(params[:id])
    if current_user.id == @car.id
      flash[:notice] = "You can not book your car!!"
      redirect_to cars_path
    else
      @booking = Booking.new
      @booking.user = current_user
      @booking.car_id = params[:id]
      @booking.save
    redirect_to mybookings_path
    end
    
  end

  def my_bookings
    @bookings = current_user.bookings
  end

  def rent_your_car
  end

  def destroy
    @booking = Booking.find(params[:booking_id])
    @booking.destroy
    redirect_to bookings_path
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_car, only: [:update, :show, :destroy, :edit]

  def index
    @cars = Car.where.not(latitude: nil, longitude: nil)
    # @cars_date = Car
    
    if params[:address].present? && params[:start_date].present? && params[:end_date].present?
      @cars = Car.search_by_address(params[:address]).where(start_date: Date.parse(params[:start_date])..Date.parse(params[:end_date]))
    elsif params[:address].present?
      @cars = Car.search_by_address(params[:address])
    else
      @cars = Car.all
    end

    @markers = @cars.map do |flat|
      {
        lng: flat.longitude,
        lat: flat.latitude
      }
    end
  end

  def edit
  end

  def show
    @user = User.find(@car.user_id)
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user

    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end

  end

  def new
    @car = Car.new
  end

  def update
    if current_user.id == @car.user_id
      if @car.update(car_params)
        redirect_to car_path(@car)
      else
        render :edit
      end
    else
      flash[:notice] = "You are not allowed to update!!!"
      redirect_to car_path(@car)
    end
  end

  def destroy
    if current_user.id == @car.user_id
      @car.destroy
      redirect_to cars_path
    else
      flash[:notice] = "You are not allowed to delete!!!"
      redirect_to car_path(@car)
    end

  end

  def find_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:make, :model, :year, :price, :photo, :address, :start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/my_bookings.html.erb
<div class="container">
    <div class="row-bookings">
      <div class="col-xs-12">
          <div class="message-header"> <h5>Your bookings</h5> </div> 
          <% @bookings.each do |booking| %>
          <div class="message">
              <div class="message-image">
                <%= cl_image_tag(booking.car.photo.filename, :width=>50, :height=>50) %>
              </div>
              <div class="message-name">
                <h3><%= booking.car.user.first_name %></h3>
                <!-- <p>Date start</p> -->
              </div>
              <div class="message-body">
                <p><strong><%= booking.car.user.address %></strong></p>
                <p>
                  <%= booking.car.make %> <%= booking.car.model %> <%= booking.car.year %>
                </p>
              </div>
              <div class="message-status">
                <p class="status pending">Cost</p>
                <p class="price"><%= booking.car.price %></p>
              </div>
          </div>
          <% end %>
       </div>
    </div>
    <div class="row-bookings">
        <div class="col-xs-12">
            <div class="message-header"><h5>Lease your vehicle</h5></div> 
          <% @bookings.each do |booking| %>
          <div class="message">
              <img class="card-user-image" src="https://kitt.lewagon.com/placeholder/users/random">
              <div class="message-name">
                <h3><%= booking.user.first_name %></h3>
                <!-- <p>Date start</p> -->
              </div>
              <div class="message-body">
                <p><strong><%= booking.user.address %></strong></p>
                <p>
                  <%= booking.car.make %> <%= booking.car.model %> <%= booking.car.year %>
                </p>
              </div>
              <div class="message-status">
                <p class="status pending">Cost</p>
                <p class="price"><%= booking.car.price %></p>
              </div>
          </div>
          <% end %>
        </div>
    </div>
</div>
<ul>
   

app/views/bookings/rent_your_car.html.erb
<div class="container">
  <h3>Here are your car bookings:</h1>
  <ul>
    <%= current_user.cars.each do |car| %>
      <li><%= car.id %></li>
      <li><%= car.make %></li>
      <li><%= car.model %></li>
      <li><%= car.year %></li>
      <li><%= car.price %></li>
      <% car.bookings.each do |booking| %>
        <li>booking : <%= booking.id %>--<%= booking.user.first_name %></li>
      <% end %>
    <% end%>
  </ul>
</div>
<!-- update -->

app/views/cars/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 ">
      <div class="form">
        <h1>Update your car</h1>
        <%= simple_form_for @car do |f|  %>
        <div class="row">
          <div class="col-xs-6">
              <%= f.input :year %>
              <%= f.input :model %>
              <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          </div>
          <div class="col-xs-6">
              <%= f.input :make %>
              <%= f.input :price %>
              <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
              <%= f.input :address %>  
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <%= f.button :submit, class: "btn-btn-primary"  %>
            </div>
        </div>
          <!-- Inject categories here -->
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<div class="search-container">
  <div class="heading-search">
    <div class="car-search-header">
      
    </div>
    <div class="form-tag">
     
    </div>
   </div> 
</div>

<div class="container">
  <h3>Start your new journey</h3>
   <%= form_tag(cars_path, method: :get) do %>
      <div class="search-field"> 
        <%= text_field_tag :address, nil, class: 'search-box', placeholder: "location" %>
        <%= text_field_tag :start_date, nil, class: 'datepicker', placeholder: "start date"%>
        <%= text_field_tag :end_date, nil, class: 'datepicker', placeholder: "end date" %>
        <%= submit_tag :Search %>
      </div>
    <% end %>

  <div class="row">
    <div class="col-xs-7">
        <div class="car-cards-title">
          <h4>Your local area's most popular cars:</h4>
        </div>
        <div class="card-container">
          <div class="row">
            <% @cars.each do |car| %>
              <% if car.photo? %>
                <% image_url = cl_image_path car.photo %>
                <% else %>
                <% image_url = "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b59fb07a91e69c940c63e04bd8b1623d&auto=format&fit=crop&w=2100&q=80" %>
              <% end %>
              <div class="col-xs-6">
                <div class="card-inner-container">
                  <div class="card">
                    <div class="card-image" style="background-image: url(<%= image_url %>);">
                    </div>
                    <div class="card-description">
                      <p><%= car.make %> <%= car.model %> <%= car.year %></p>
                    </div>
                    <div class="card-description">
                      <p><strong>$<%= car.price %> per day </strong></p>
                    </div>
                    <div class="card-user">
                      <img class="card-user-image" src="https://kitt.lewagon.com/placeholder/users/random">
                      <div class="card-user-description"><%= car.user.first_name %></div>
                      <div class="card-user-link">
                        <%= link_to 'Show', car_path(car) %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      
    </div>
    <div class="col-xs-5">
      <div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>"></div>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="form">
        <h1>Add your car</h1>
        <%= simple_form_for @car do |f|  %>
        <div class="row">
          <div class="col-xs-6">
              <%= f.input :year %>
              <%= f.input :model %>
              <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          </div>
          <div class="col-xs-6">
              <%= f.input :make %>
              <%= f.input :price %>
              <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
              <%= f.input :address %>  
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
              <%= f.input :photo %>
              <%= f.input :photo_cache, as: :hidden %>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <%= f.button :submit, class: "btn-btn-primary"  %>
            </div>
        </div>
          <!-- Inject categories here -->
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container">
  <h1><%= @user.first_name %>'s Car</h1>
  <div class="car-flex">
    <div class="car-image">
        <%= cl_image_tag @car.photo.filename, class: "" %>
    </div>
    <div class="right-side">
      <h2><%= @car.year %> <%= @car.make %> <%= @car.model %></h2><br><br><br><br>
      <p>$<%= @car.price %> p/d</p>
    </div>
  </div>
  <p class='booking-tool'><%= link_to "Book Now", booking_car_path(@car), class:'book-btn'%></p>
    <% if current_user == @car.user %>
      <%= link_to "Edit", edit_car_path(@car), class:'flex-tools'%>
      <%= link_to "Delete", car_path(@car), method: :delete, class:'flex-tools'%>
    <% end %>
      <%= link_to "Dashboard", rentyourcar_path, class:'flex-tools'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Car Space</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>   
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag "map", "application" %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Cars Space</h1>
    <p> <span id="banner-typed-text"></span></p>
    <a href="/cars" class="btn btn-primary btn-lg">Drive A Car</a>
    <a href="/cars/new" class="btn btn-primary btn-lg">Lease Your Car</a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

     <%= link_to "Drive A Car", cars_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <%= link_to "Lease Your Car",new_car_path , class: "navbar-wagon-item navbar-wagon-link" %>

    <% if user_signed_in? %>
      <%= link_to "Your Bookings", mybookings_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/random", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>